# Generated by Django 2.2 on 2021-12-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DV_HFMD', '0002_vnpopulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('male', models.IntegerField()),
                ('female', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='VNpopulation',
        ),
    ]
